name: Challenge 02
on: push
jobs:
  job1:
    name: Ubuntu Job
    runs-on: ubuntu-latest
    run: date
  job2:
    name: Windows Job
    runs-on: windows-latest
    run: Get-Date
  job3:
    name: Macos Job
    runs-on: macos-latest
    run: date
  job4:
    name: Depending Job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    run: date
    