name: Challenge 03

on: [push]

env:
  ARTIFACT_NAME: artifact

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./build
